#
# check the doc at
# https://goreleaser.com/customization/build/
#
project_name: domain-checker
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
