name: Linting

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: Linting Go code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
